[build]
  base = "frontend"
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (Netlify UI'dan set edilecek)
# VITE_API_URL = https://your-backend-api.com

[context.production]
  command = "npm install && npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm install && npm run build"
  publish = "dist"

[context.branch-deploy]
  command = "npm install && npm run build"
  publish = "dist"
